name: Deploy to neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Neocities
      uses: jonchang/deploy-neocities@v1
      with:
        key: ${{ secrets.NEOCITIES_API_TOKEN }}
        dir: ./
        clean: false