name: Deploy static content to Neocities

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

concurrency:
  group: "neocities"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public